USE DataWarehouseAnalytics
--MAGNITUDE ANALYSIS
	
	--Find the total no. of customers by countries
		SELECT country,
		COUNT(customer_key) AS total_customers
		FROM gold.dim_customers
		GROUP BY country
		ORDER BY total_customers DESC

	--Find total customers by gender
		SELECT
		gender,
		COUNT(customer_key) AS total_customer
		FROM gold.dim_customers
		GROUP BY gender
		ORDER BY total_customer DESC

	--Find total products by category
	 SELECT
	 category,
	 COUNT(product_key) AS total_products
	 FROM gold.dim_products
	 GROUP BY category
	 ORDER BY total_products DESC

	--What is the avg costs in each category
		SELECT
		category,
		AVG(cost) AS avg_cost
		FROM GOLD.dim_products
		GROUP BY category
		ORDER BY avg_cost DESC

	--What is total revenue generated for each category
		SELECT
		P.category,
		SUM(F.sales_amount) AS total_revenue_generated
		FROM gold.fact_sales AS F
		LEFT JOIN gold.dim_products AS P
		ON F.product_key = P.product_key 
		GROUP BY P.category
		ORDER BY total_revenue_generated DESC

	--Find total revenue generated by each customer
		SELECT
		C.customer_key,
		CONCAT(C.first_name,' ',C.last_name) AS cust_name,
		SUM(F.sales_amount) AS total_revenue
		FROM gold.fact_sales AS F
		LEFT JOIN gold.dim_customers AS C
		ON F.customer_key = C.customer_key
		GROUP BY C.customer_key, CONCAT(C.first_name,' ',C.last_name)
		ORDER BY total_revenue DESC 

	--What is the distribution of sold items across countries?
		SELECT
		C.country,
		SUM(F.quantity) AS dist_of_sold_items
		FROM gold.fact_sales AS F
		JOIN gold.dim_customers AS C
		ON F.customer_key = C.customer_key
		GROUP BY C.country
		ORDER BY dist_of_sold_items DESC